import { font } from "@/utils/config"
import "../styles/globals.scss";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={font.className}>
                {children}
                <ToastContainer position='top-left' />
            </body>
        </html>
    )
}